sudo: false
dist: trusty
language: c++

addons:
  apt:
    packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - g++
    - clang

before_script:
- mkdir build && cd build
- cmake .. -G"$GENERATOR" $CMAKE_FLAGS -DSFML_BUILD_TEST_SUITE=TRUE -DSFML_BUILD_EXAMPLES=TRUE

script:
- sudo cmake --build . --target install

matrix:
  include:

  # Linux - gcc
  - os: linux
    compiler: gcc
    env:
    - GENERATOR="Unix Makefiles"
    - CMAKE_FLAGS=""

  # Linux - clang
  - os: linux
    compiler: clang
    env:
    - GENERATOR="Unix Makefiles"
    - CMAKE_FLAGS=""

  # macOS - Xcode 10
  - os: osx
    osx_image: xcode10
    env:
    - GENERATOR="Xcode"
    - CMAKE_FLAGS="-DSFML_BUILD_FRAMEWORKS=TRUE"

  # iOS - Xcode 9
  - os: osx
    osx_image: xcode10
    env:
    - GENERATOR="Xcode"
    - CMAKE_FLAGS="-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/iOS.toolchain.cmake -DIOS_PLATFORM=SIMULATOR"

notifications:
  email: false
